environment:
  access_token:
    secure: fdd2f1bbc22dccd0df98d690ffafecb6dad0070f

install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force

    Invoke-WebRequest -UseBasicParsing -OutFile C:\projects\dockerpester\docker-19.03.5.zip https://download.docker.com/components/engine/windows-server/19.03/docker-19.03.5.zip

    Expand-Archive docker-19.03.5.zip -DestinationPath $Env:ProgramFiles -Force

    Remove-Item -Force docker-19.03.5.zip

    Install-WindowsFeature Containers

    $env:path += ";$env:ProgramFiles\docker"

    $newPath = "$env:ProgramFiles\docker;" 

    [Environment]::SetEnvironmentVariable("PATH", $newPath,[EnvironmentVariableTarget]::Machine)

    dockerd --register-service

    Start-Service docker

- ps: >-   
    Powershell
    Docker pull mcr.microsoft.com/powershell:7.0.0-rc.2-alpine-3.8
    
build: off
test_script:
- ps: >- 
    .\CI\build.ps1

    Import-Module Pester 

    Invoke-Pester .\Tests\BaseTests