environment:
  access_token:
    secure: fdd2f1bbc22dccd0df98d690ffafecb6dad0070f

install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force

    Install-Module DockerMsftProvider -Force
    Install-Package Docker -ProviderName DockerMsftProvider -Force

    Install-WindowsFeature Containers 

    Docker pull mcr.microsoft.com/powershell:7.0.0-rc.2-alpine-3.8
    
build: off
test_script:
- ps: >- 
    .\CI\build.ps1

    Import-Module Pester 

    Invoke-Pester .\Tests\BaseTests