environment:
  access_token:
    secure: fdd2f1bbc22dccd0df98d690ffafecb6dad0070f

install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force

    Invoke-WebRequest -UseBasicParsing -OutFile c:\docker-19.03.5.zip https://download.docker.com/components/engine/windows-server/19.03/docker-19.03.5.zip

    cd c:

    # Extract the archive.
    Expand-Archive docker-19.03.5.zip -DestinationPath $Env:ProgramFiles -Force

    # Clean up the zip file.
    Remove-Item -Force docker-19.03.5.zip

    # Install Docker. This requires rebooting.
    $null = Install-WindowsFeature containers

    # Add Docker to the path for the current session.
    $env:path += ";$env:ProgramFiles\docker"

    # Optionally, modify PATH to persist across sessions.
    $newPath = "$env:ProgramFiles\docker;" +
    [Environment]::GetEnvironmentVariable("PATH",
    [EnvironmentVariableTarget]::Machine)

    [Environment]::SetEnvironmentVariable("PATH", $newPath,
    [EnvironmentVariableTarget]::Machine)

    # Register the Docker daemon as a service.
    dockerd --register-service

    # Start the Docker service.
    Start-Service docker

- ps: >-    
    Docker pull mcr.microsoft.com/powershell:7.0.0-rc.2-alpine-3.8
    
build: off
test_script:
- ps: >- 
    .\CI\build.ps1

    Import-Module Pester 

    Invoke-Pester .\Tests\BaseTests